services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=super-secret-key
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydatabase
      - FLASK_APP=run.py
    volumes:
      - .:/app
    command: >
      sh -c "
        flask db migrate -m 'autogen email' &&
        flask db upgrade &&
        python run.py
      "

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  pgdata: {}
  pgadmin_data:
