version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    entrypoint:
      - SECRET_KEY= super-secret-key
      - DATABASE_URL, postgresql://postgres:postgres@db:5432/mydatabase
    volumes:
      - .:/app
    command: python run.py

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
